# TODO: Use Ubuntu 22.04 as base image

# TODO: Install build dependencies (cmake, build-essential, python3-pip)

# TODO: Install Conan

# TODO: Copy source code and conanfile

# TODO: Build the project

# TODO: Set CMD to run the executable
