-- TODO: Design a table for Cameras
-- CREATE TABLE Cameras ...

-- TODO: Design a table for Frames (referencing image file paths)
-- CREATE TABLE Frames ...

-- TODO: Design a table for Detections (referencing Frames)
-- CREATE TABLE Detections ...
